name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
        - name: Install Qt
          uses: jurplel/install-qt-action@v4
          with:
            version: '5.15.2'
            arch: 'gcc_64'
            archives: qtbase qtsvg qttools qtx11extras
            cache: true
